### ISSUE TITLE
Panel doesn't expand well in multi window/display scenario.

### ISSUE THREAD

**Issue by wouterroos** [nbelyh/VisioPanelAddinVSTO#4]
Hi, 

When trying the panel on a multiple document window Visio instance (see image) or with multiple displays, the panel doesn't expand properly. I'm guessing that it has something to do with the `CreateWindow()` implementation in the `PanelFrame` class. I've tried to set the `nTop` and `nLeft` arguments of the `Windows.Add()` method to the size of the Visio document window, which does seem to help a bit. It now works properly on both displays with a single document window, but I'm still struggling to get it to work for multiple document windows in a single Visio instance. The problem is that I can't seem to figure out what determines the amount of space the panel is allowed to consume. Are you able to reproduce this issue, and do you have any ideas on how we can improve this behavior?

I do want to mention that I've modified your implementation so that it works with WPF instead of Windows Forms, but from what I've seen in my tests, switching to Windows Forms doesn't change the behavior described above.

![image](https://user-images.githubusercontent.com/5137829/34301241-16466096-e72c-11e7-8f77-fcabb51557b3.png)

**Comment by nbelyh** [comment]
Just came across the issue. I am able to reproduce the issue, still no fix for now (Windows 10, multi-monitor, per-monitor resolution setup). Visio API just does not "want" to show the window, no matter what size you set 😅
